matrix:
  include:
    - language: node_js
      os: linux
      dist: trusty
      node_js: 8
      addons:
      apt:
        packages:
        - libsecret-1-dev
        - libxss-dev
        - pkg-config
      install:
        - npm install
      script:
        - npm run dist:lin
