image:
- Visual Studio 2017
- Ubuntu1804

branches:
  except:
    - l10n_master

stack: node 10

init:
- sh: sudo apt-get update
- sh: sudo apt-get -y install pkg-config libxss-dev libsecret-1-dev rpm
- ps: |
    if($isWindows) {
      Install-Product node 10
    }

install:
- ps: |
    $packageVersion = (Get-Content -Raw -Path .\src\package.json | ConvertFrom-Json).version
    $prodDeploy = $false
    if($env:APPVEYOR_REPO_TAG -eq "true" -and $env:APPVEYOR_RE_BUILD -eq "True") {
      $prodDeploy = $true
      echo "This is a production deployment."
    }
    if($isWindows) {
      choco install cloc --no-progress
      cloc --include-lang TypeScript,JavaScript,HTML,Sass,CSS --vcs git
    }

before_build:
- node --version
- npm --version

build_script:
- npm install
- ps: |
    if($isLinux) {
      npm run dist:lin
      Push-AppveyorArtifact ./dist/Bitwarden-${packageVersion}-x86_64.AppImage
      Push-AppveyorArtifact ./dist/bitwarden_${packageVersion}_amd64.snap
      Push-AppveyorArtifact ./dist/Bitwarden-${packageVersion}-amd64.deb
      Push-AppveyorArtifact ./dist/Bitwarden-${packageVersion}-x64.freebsd
      Push-AppveyorArtifact ./dist/Bitwarden-${packageVersion}-x86_64.rpm
    }
    else {
      npm run dist:win:ci
      Push-AppveyorArtifact .\dist\Bitwarden-Portable-${packageVersion}.exe
      Push-AppveyorArtifact .\dist\nsis-web\Bitwarden-Installer-${packageVersion}.exe
      Push-AppveyorArtifact .\dist\Bitwarden-${packageVersion}-x64.appx
      Push-AppveyorArtifact .\dist\Bitwarden-${packageVersion}-ia32.appx
    }

after_build:
- ps: |
    if($prodDeploy) {
      if($isLinux) {
        echo "Deploy Linux..."
      }
      else {
        echo "Deploy Windows..."
      }
    }

for:
- 
  matrix:
    only:
      - image: Visual Studio 2017
  cache:
  - '%LOCALAPPDATA%\electron -> appveyor.yml'
  - '%LOCALAPPDATA%\electron-builder -> appveyor.yml'

-
  matrix:
    only:
      - image: Ubuntu1804
  cache:
  - '/home/appveyor/.cache/electron -> appveyor.yml'
  - '/home/appveyor/.cache/electron-builder -> appveyor.yml'
