image:
#- Visual Studio 2017
- Ubuntu1804

branches:
  except:
    - l10n_master

stack: node 10

init:
- ps: |
    if($isWindows) {
      Install-Product node 10
    }

install:
- sh: sudo apt-get update
- sh: sudo apt-get -y install pkg-config libxss-dev libsecret-1-dev rpm
- ps: $env:package_version = (Get-Content -Raw -Path .\src\package.json | ConvertFrom-Json).version
- ps: |
    if($isWindows) {
      choco install cloc --no-progress
      cloc --include-lang TypeScript,JavaScript,HTML,Sass,CSS --vcs git
    }

before_build:
- node --version
- npm --version

build_script:
- npm install
- ps: |
    if($isLinux) {
      npm run dist:lin
      Push-AppveyorArtifact ./dist/Bitwarden-$env:package_version-x86_64.AppImage
      Push-AppveyorArtifact ./dist/bitwarden_$env:package_version_amd64.snap
      Push-AppveyorArtifact ./dist/Bitwarden-$env:package_version-amd64.deb
      Push-AppveyorArtifact ./dist/Bitwarden-$env:package_version-x64.freebsd
      Push-AppveyorArtifact ./dist/dist/Bitwarden-$env:package_version-x86_64.rpm
    }
    else {
      npm run dist:win:ci
      Push-AppveyorArtifact .\dist\Bitwarden-Portable-$env:package_version.exe
      Push-AppveyorArtifact .\dist\nsis-web\Bitwarden-Installer-$env:package_version.exe
      Push-AppveyorArtifact .\dist\Bitwarden-$env:package_version-x64.appx
      Push-AppveyorArtifact .\dist\Bitwarden-$env:package_version-ia32.appx
    }

cache:
- '~/.cache/electron -> appveyor.yml'
- '~/.cache/electron-builder -> appveyor.yml'
- '%USERPROFILE%\.electron -> appveyor.yml'
